hash-format = "sha256"

[[files]]
file = "config/ProjectE/client.toml"
hash = "96fba58076ce3ff6f8dbbe8b43b70bcdf73c3d6a1fdb78074bd9437cd7c065dd"

[[files]]
file = "config/bcc-common.toml"
hash = "a4e6330b03edab84b0b9a29e9eab4652c2806b11baf11834e9dfe436fbbadd77"

[[files]]
file = "config/blue_skies-client.toml"
hash = "071d402fc522364f0bbbe1cce75c96800c5f4bf0236dcf6766a948180d7ed595"

[[files]]
file = "config/create-client.toml"
hash = "57e54ba2fc5fed6544842876f9e63e732e280f4cadad732b08aa4a3928559f22"

[[files]]
file = "config/drippyloadingscreen/config.cfg"
hash = "4a8e1f8287e0804bf5bd6490735c3668c46d0063546af4bdafaf280d32754fbb"

[[files]]
file = "config/drippyloadingscreen/customization/loading.dllayout"
hash = "f24f6c52c46ec95f736c356661a419ee33a7c75f389ca44712c69eea41882b1c"

[[files]]
file = "config/enigmaticlegacy-client.omniconf"
hash = "c640bb9d1d1d9a47e5a113126e384e9bccf5409bc52837e28c9622cb8c399d3b"

[[files]]
file = "config/fancymenu/config.txt"
hash = "e9df0449ac60265e7358a759f4a227b86523bc2e072f2c7c21508f0ab5a98b01"

[[files]]
file = "config/fancymenu/custom_locals/pack/en_us.local"
hash = "c2f0cef18f72cadbbcc93510fef14946e56d4434fef34a352734c9214c310bee"

[[files]]
file = "config/fancymenu/custom_locals/pack/ru_ru.local"
hash = "30ba07f938617c4a3c533a10cf24e579c0a80061a02d7236ffcf11aba2d3c51a"

[[files]]
file = "config/fancymenu/custom_locals/pack/uk_ua.local"
hash = "4757c3e9016a7c9886651abe07f37c94084e52cc87f4a51afd5adca2c42bf34b"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "4c68ab99c906dd487952f61bf33c0635039a8bbff3f02099e3cd8272fe51b4aa"

[[files]]
file = "config/fancymenu/customization/Menu.txt"
hash = "f2f85ecf8843fcefa5169ed06a44360dbb53b9832048bd942b486c1a4c75ad86"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon16x16.png"
hash = "0a1540df23c9d79ce703b691b077df0d6e49dec5d627148686d9a3c03147cb5e"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon32x32.png"
hash = "d5d6716f7fdbd58e12bf64cc777b95678e8527c4e87e0aeffdae373520b23a7b"

[[files]]
file = "config/fancymenu/resources/background.png"
hash = "3f7572f2328551f7bea456cf661cb4fe4a4fc6ee9dde769c6ad80956c97c6fe0"

[[files]]
file = "config/fancymenu/resources/logo.png"
hash = "975d2b104e7bfd1a6735bedc9eff04700f79062ca5fee0b96b36b40c98cc3a96"

[[files]]
file = "config/fancymenu/resources/pack_version.txt"
hash = "eca06fdd26e513a7b8510c86602285041a916de5491de13373d94fe0d7e04737"

[[files]]
file = "config/greekfantasy-common.toml"
hash = "0df0e5eb593a4b876f13ef6bcb45c456005db7b0325f0b8d0a4ae41b556241af"

[[files]]
file = "config/openloader/advanced_options.json"
hash = "97c64147276f55cad728249dd77602661e2327fa178aeb8e0db12866df448211"

[[files]]
file = "config/openloader/data/repurposed-structures-better-dungeons-datapack.pw.toml"
hash = "e33602eeae50447d004c33c2ecbe8b9c6f9fd7a0b63b4d82ae94818f6e8172aa"
metafile = true

[[files]]
file = "config/openloader/resources/GamersReloaded Resources/assets/apotheosis/lang/ru_ru.json"
hash = "5f4b6502fb99350ed5ef9ae59185603c24186235ac904f34fb5120bf2bbfe3f1"

[[files]]
file = "config/openloader/resources/GamersReloaded Resources/assets/brewinandchewin/lang/ru_ru.json"
hash = "044dcc7bb600daa422ac47f62032e6bc93f930f391745427fae3c7866dd0a4b6"

[[files]]
file = "config/openloader/resources/GamersReloaded Resources/assets/create_sa/lang/ru_ru.json"
hash = "3be370ffdc76622f3e2215072068cf053ee1fc29a4d8ca5fd2e0264dbc03ae9f"

[[files]]
file = "config/openloader/resources/GamersReloaded Resources/assets/moremekanismprocessing/lang/ru_ru.json"
hash = "06e88de4d2d8744332d9c290d8a06f887a66e0197695cf5fc4b35f438539df31"

[[files]]
file = "config/openloader/resources/GamersReloaded Resources/pack.mcmeta"
hash = "6a6ebac7a4b043497eae05aec062495abebba7fff3456db9f0b3a844ad46b5a0"

[[files]]
file = "config/openloader/resources/Tutta's_MCA_Texture_V1.15+-+1.18+.zip"
hash = "fc96966b4ffe0e936022de7f781243e702f3c046643eb2046a215b74242c04bf"

[[files]]
file = "config/quark-common.toml"
hash = "94e78cb8c6b66471e8e9a4967e157a313addababb86204cd459943c5487a82be"

[[files]]
file = "config/securitycraft-client.toml"
hash = "b96d295ea206bd9c79a3be58ec4a0a9859bb55b6c96d7e4b59af0c03727cfa71"

[[files]]
file = "config/vampirism-common.toml"
hash = "e95233f172ea58f4262d08472073a97683d5489e38e52b3cde7ac7318db7af5c"

[[files]]
file = "defaultconfigs/xaerominimap.txt"
hash = "90741f72845b38d63b542fefcdc4e67fd3c068e511cb53dd22db3975a7fc7f9c"

[[files]]
file = "mods/apotheosis.pw.toml"
hash = "bf3d5e86acf5331a02cbf6d9717c94c55fd4fc675f8690a51cd13f8ba499e8b6"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "3cacdb43b158d024f33eda4364c70c8fe15f02ad93011ef44b2e894f9b709ce3"
metafile = true

[[files]]
file = "mods/applied-mekanistics.pw.toml"
hash = "1440014a95f25f1d02b824e63f8dcd3654f042cc6058718d7c626f61e05a04ac"
metafile = true

[[files]]
file = "mods/autoreglib.pw.toml"
hash = "4b9f680bd2c3c2efc44ce41626b2fe5860403a4ec38309ab6fd8a04bac16e8bc"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "9131c77d39b6d4cb198739eda45560416bfc2ee08c6cb5973a2e3435266ea5e5"
metafile = true

[[files]]
file = "mods/blue-skies.pw.toml"
hash = "acee936dece13a20480102ee02af50b5a474dc9db7c1170be230a0bbb157f60c"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "7241f3d873b2856258856d9c0601aa5438428d95317227d726bc4c451c51a7fa"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "8aa8cf66f38711e70abb448f0b467095cef3be6608b4305c8c0971eee86f394f"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "1e6231c40cf9f2ee400cc0af792fdc5d45b2f926412f07fe687959de6abbc064"
metafile = true

[[files]]
file = "mods/corail-tombstone.pw.toml"
hash = "3c3db9fb1d218f312693d378fee72943b64fe6e0e3e0df172887a12419754724"
metafile = true

[[files]]
file = "mods/create-misc-and-things.pw.toml"
hash = "742a9f78528742435f58af062cff491595aca212d201557e92bd120f402c7877"
metafile = true

[[files]]
file = "mods/create-stuff-additions.pw.toml"
hash = "35d229d30cf14fc5d0244ea2f43ef22c3f94a35523b0afeed3826798c5e4e6b2"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "550373c6cde926832ea77f0d5e6fda708e37323468caca5a32d8ae9b88baeea7"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "9dbcda8ffbaedfdf3dcecf7af271a19e1fa886c27516bec6fda4606a36518a42"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "90aa116eec4074f4cb6aea2fa04d457a870f686fc1d97aa568d21192b1d007c3"
metafile = true

[[files]]
file = "mods/cyclic.pw.toml"
hash = "14ec065bbd4fb51623f1e4259732335ddf7a085807ee08b41ba30595196e2dcf"
metafile = true

[[files]]
file = "mods/cyclops-core.pw.toml"
hash = "80a4fb51fe646c4f56c6cef6950dfb4ec90a948e26f3c6024fb9bfc3027e5fa6"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
hash = "605f32ad7d8999c3bbd4af14926ef0f8566142b73d4d0e8a732e6eef93a95ac6"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "561427196527da44ce65f6971d6f611dd00e1f56b54a51bdf90b4b9019a4a785"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "03f5a2eb3c7c2c871f8a3b3ac0235291d41e70ac4baa22e9c9140e358b8773ab"
metafile = true

[[files]]
file = "mods/enhanced-celestials.pw.toml"
hash = "6e4a34c104bf7f0754535a7738369b5da8ec28afa98fd7cfff583185da0a66ec"
metafile = true

[[files]]
file = "mods/enigmatic-legacy.pw.toml"
hash = "ce755dc205b74e58431c2e40422a1cfcff5e9c6ca7f2d25c7ec5cd537193888d"
metafile = true

[[files]]
file = "mods/evilcraft.pw.toml"
hash = "0201b4236a31324a6a65d2bf1c0b124578287f20a5cc66832004d1b8d9d8b42d"
metafile = true

[[files]]
file = "mods/fancymenu-forge.pw.toml"
hash = "fb12c72525fb1b71f955624bdf748bce45f358884394da51d67025a8f4ac6640"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "546cf7bd63e02041e8d159ecc5326fde952aaeaf0d8517b5eb5f552a84fcf12a"
metafile = true

[[files]]
file = "mods/feature-nbt-deadlock-be-gone.pw.toml"
hash = "44c2de08592e5c0dad820b217b0fd332db0757a344796f1e01806cfe881206bc"
metafile = true

[[files]]
file = "mods/flywheel.pw.toml"
hash = "9e0ad54ad0766fce2609aebb53f9f4e3a4b67dab325990fb498ef178e933b7a5"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "e2ecdb0eaa4c2118a320126f5993f781a302d8dec01a041374d5381ed54d6a44"
metafile = true

[[files]]
file = "mods/greek-fantasy.pw.toml"
hash = "7fec8ba384979fe7ef8ebb41cfbde024a255cac66e758e000cf8566cc6b7b296"
metafile = true

[[files]]
file = "mods/guide-api-village-and-pillage.pw.toml"
hash = "52c76dca73ede428d7d515279a5d22847312a8d3abc055494aec60e1e56a712f"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
hash = "d1bbd184728c09526bdd18a1c629a55b5a2ccfdc792296cecc870317f7fd3a78"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "73c49d7dae3c411d64ec5b77544d66e0cc513b5b37b9f70f80bf38a78d5f138a"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "d673098f8970c1882fba317165683a616400e53145fe619d5944af8fdeb9976b"
metafile = true

[[files]]
file = "mods/libx.pw.toml"
hash = "1abd6b14897b96bd995cca1da58bffc0637207f4854fe7afd1fe9aad228988a7"
metafile = true

[[files]]
file = "mods/mana-and-artifice.pw.toml"
hash = "912c22ba96ab5abbbc24fdffa68f95a1f21d9360ac39bb05f4dc5b3777dfc11f"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "9f33ad46094198693346e70eb7311d195c3b5adfa54c82c6b9f3116403b37ee3"
metafile = true

[[files]]
file = "mods/mcjtylib.pw.toml"
hash = "0c4037041d6e546c141984f8294166af45c729f5ff536d811a23d65973d807c0"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
hash = "5509ff135d46d354664720f02f182bda6ba8697f22b49a42a8cf02aef6112763"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "f0684891c05b13f481c137fd14a77a41614bc37e226af07e1ad42cb85221cc90"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
hash = "d234f16017228f2bd379122c731bc62496b073742cf61f1d87f24b9af4b53c15"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "ec1b184fe352b65db298ce3c93b66aa2c12a5b0a6ea1ef9a576179a1523b0264"
metafile = true

[[files]]
file = "mods/minecraft-comes-alive-reborn.pw.toml"
hash = "c51279d7ceeb2370b7ca92f5dc50741cbebc7d9c58ae3ea9119fae795c95ba48"
metafile = true

[[files]]
file = "mods/more-mekanism-processing.pw.toml"
hash = "fea1c7d6b98b6606ae17a2e436d7158dd1ec86c29c8af4a500b42d66fa70a00e"
metafile = true

[[files]]
file = "mods/mrcrayfish-furniture-mod.pw.toml"
hash = "916c4cb1f3e1a95e6c52cdcac101fdc54ce5e4d1cb568493de2b6bef26a2a8ad"
metafile = true

[[files]]
file = "mods/mythicbotany.pw.toml"
hash = "548b6245f3345e5a1a1754022c03a6f359ac76803e6fd57ef7ec0e7ddf9867cd"
metafile = true

[[files]]
file = "mods/name-pain.pw.toml"
hash = "63b6fdd64cae2366e75e9ce4c08d09743453c2e367b355c80ca4eea175a36e4c"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "ae4c3617170709ac560c8113f1526193e79750735d12bbc2d5119f518b866799"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "3708d138fcfc8f482eb70c2109af2d2e544a20d9b9aeadd36955e43fd5055d87"
metafile = true

[[files]]
file = "mods/polylib.pw.toml"
hash = "dc5355c75b3a14c1d0735f6db571f07aae00ca531bdb471aebaf89addcda5a4e"
metafile = true

[[files]]
file = "mods/projecte.pw.toml"
hash = "824ad9a385cce61265f09bbc1eb1666756a8ba84a3870e4bed9a92b5ce7a70f8"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "323bf0949b42dbb97a7c35d17f436a7b2c7eb463cc97f46a54469ff3a0bad027"
metafile = true

[[files]]
file = "mods/repurposed-structures.pw.toml"
hash = "909d188027943b867bd50adb6ab2f5dca934c2ea8480e5eb0f965c90c64e0f0b"
metafile = true

[[files]]
file = "mods/rftools-base.pw.toml"
hash = "ce2fdaac17c20454cbcd0f1069f193d1f2b60bfeb56ce4e1c3314014930aa39a"
metafile = true

[[files]]
file = "mods/rftools-dimensions.pw.toml"
hash = "ee8ef99ac73281f974a2e4688c933cd1369698a567b4a28f68c310389e8ba586"
metafile = true

[[files]]
file = "mods/rftools-utility.pw.toml"
hash = "3fc20703f48e3123dcd6af016d389cea7bfd4643132720211b1727e88a98bbde"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "c3388926628a60785680764af196ec0ff0df25790f75abe61cfb731b5a469e97"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "26e591b0b07c8ef07f887eaf3feee21d564c891418e3da0304b39972d6ffb106"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "b34952ddd6841882e2ece139e1b2c7ce9573e866b914e3c52917f3caf0d2f450"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
hash = "d6874f78491a6e89c5f25bd6356469080160dd39d4032e8262947f95ae4729d0"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "0753b3791b2815ec7948210412b0404e7dce473bb62270b7398a7458614b2878"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "380381a01ac5af796b67dd4bcef0feb312d64af4d30ad92fe249a7b70b0df811"
metafile = true

[[files]]
file = "mods/structure-gel-api.pw.toml"
hash = "809dfff943976dd9e8c11721ddcdcdf3130e0f9b3ae67bf98089f3cb5e056222"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "5f62a1b53954ac5f25d506f24755c7bde75b179895219260612f4ccad31bf2c5"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "2fbe8c620f5869a9198461492f7e8ab9e57f5315c4176691cc4e02b04d94d683"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "2891bea6bfecd71e0061b6bef435641bfa5508de525280702a37af894327b428"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "526f1411f2287247b09ebe85ce4ba29daaad56f1a817d163ec194f78b11bb8ef"
metafile = true

[[files]]
file = "mods/the-graveyard-biomes-forge.pw.toml"
hash = "b078041ef1a2eb142a3f99bb08da9d8d30f6607eb097d39c56cfd8669e1ca696"
metafile = true

[[files]]
file = "mods/the-graveyard-forge.pw.toml"
hash = "4e5ab66552e294ec1d88c473a84d900dc907a38f5c63d3539bb05522bbb9001e"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "340e1fb9df4501861e779df3a20188653a43d0c61023237d4f936490fc527ca7"
metafile = true

[[files]]
file = "mods/vampirism-become-a-vampire.pw.toml"
hash = "4e10abf415163f490fe3ca8f353b7564dd97086b8d89c84e3e8edccf2a027799"
metafile = true

[[files]]
file = "mods/vampirism-integrations.pw.toml"
hash = "aa3b5446770af49e5555517eeb925d821b093dd8235ff53d08e94b8b10a91c5f"
metafile = true

[[files]]
file = "mods/werewolves-become-a-beast.pw.toml"
hash = "cfc3d174936dcb732635b458f4dc42d5144dbccf0032ff33b51a7cba63762271"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "01399fef27404a511bfc9b6dad93773e1847c394e86d258d4fa1f3ef9171288c"
metafile = true

[[files]]
file = "mods/wireless-chargers.pw.toml"
hash = "2242d4beed8485a84b9f54d7cfbde96d634b2420ec0bf9642be6dacbd94f549a"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "3ad22abe04558e12f7374836819e9aa716a2965cbed02c92796371c2b5bf82ba"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "4f45581bac450b01fbbb56a39cf908e57dc81260e4ab6ffd8303ca62c53b421c"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "52b3c9b4326bb2572e175ebf6d820ca400bf0c4679d7d2c23fbd5cc3c4e02781"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "799ba57de8c96266d2bec8f18ea749721394e1fdb8b4e95d90ce66a1f87cd3e1"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "2eae47e79517a349e5c76ab4228254d1cbebcdaeb32ee1ee69026b888caaf970"
metafile = true
